### ISSUE TITLE
Error starting application

### ISSUE THREAD

**Issue by ahazu** [cyber-defence-campus/RemoteIDReceiver#4]
Hi team, 

I'm getting the following when trying to start the application:

```
┌──(kali㉿kali)-[~/RemoteIDReceiver/Receiver]
└─$ python ./backend/dronesniffer/main.py -p 80
2023-12-11 08:01:37,316 main INFO Setting up database...
2023-12-11 08:01:37,317 info_handler INFO setting up database and tables
2023-12-11 08:01:37,319 main INFO Starting sniff manager...
Traceback (most recent call last):
  File "/home/kali/RemoteIDReceiver/Receiver/./backend/dronesniffer/main.py", line 66, in <module>
    main()
  File "/home/kali/RemoteIDReceiver/Receiver/./backend/dronesniffer/main.py", line 56, in main
    settings = get_settings()
               ^^^^^^^^^^^^^^
  File "/home/kali/RemoteIDReceiver/Receiver/backend/dronesniffer/settings.py", line 15, in get_settings
    settings = Settings()
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
google_maps_api_key
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-11 08:01:37,320 sniffers INFO Stopping all sniffers...
2023-12-11 08:01:37,321 sniffers INFO All sniffers were stopped successfully.
```

I tested it on Kali 2023.3 and Kali 2023.4. Looks like it wants the google maps API key before I've had a chance to set it.

**Comment by llorencroma** [comment]
could you try now? I added the None value explicitly by default into the variable that stores the google maps api key.
`google_maps_api_key: Optional[str] = None`

Apparently pydantics requires an initialization value

**Comment by ahazu** [comment]
That was fast! And yes, it fixed the issue. 👍
